# config.yaml
baseURL: "https://KillerShoaib.github.io/"
languageCode: en-us
title: AI With Shoaib
theme: LoveIt
enableInlineShortcodes: true
enableEmoji: true

author:
  name: Shoaib Hossain
  email: "sh.shoaib8@gmail.com"
  link: "https://reliable-chimera-d33c1f.netlify.app/"

languages:
  en:
    weight: 1
    title: AI With Shoaib
    languageCode: en
    languageName: English
    menu:
      main:
        - weight: 1
          identifier: posts
          pre: ""
          post: ""
          name: Posts
          url: /posts/
          title: ""
        - weight: 3
          identifier: tags
          pre: ""
          post: ""
          name: Tags
          url: /tags/
          title: ""
        - weight: 2
          identifier: categories
          pre: ""
          post: ""
          name: Categories
          url: /categories/
          title: ""

        - weight: 4
          identifier: deep learning
          pre: ""
          post: ""
          name: Deep Learning
          url: /categories/deep-learning/
          title: ""
        
        - weight: 5
          identifier: about
          pre: ""
          post: ""
          name: About
          url: /about/
          title: ""
  bn:
    weight: 2
    title: AI With Shoaib
    languageCode: bn
    languageName: বাংলা 
    hasCJKLanguage: true
    menu:
      main:
        - weight: 1
          identifier: posts
          pre: ""
          post: ""
          name: পোস্ট
          url: /posts/
          title: ""
        - weight: 3
          identifier: tags
          pre: ""
          post: ""
          name: ট্যাগ
          url: /tags/
          title: ""
        - weight: 2
          identifier: categories
          pre: ""
          post: ""
          name: বিভাগ
          url: /categories/
          title: ""

        - weight: 4
          identifier: deep learning
          pre: ""
          post: ""
          name: ডিপ লার্নিং
          url: /categories/deep-learning/
          title: ""

        - weight: 5
          identifier: about
          pre: ""
          post: ""
          name: লেখক পরিচিতি
          url: /about/
          title: ""
    params:
      home:
        profile:
          enable: true
          gravatarEmail: ""
          avatarURL: /images/ezgif.com-gif-maker (1).gif
          title: AI With Shoaib
          subtitle: সহজ বাংলায় ডিপ লার্নিং, মেশিন লার্নিং, কম্পিউটার ভিশন এবং ন্যাচারাল ল্যাঙ্গুয়েজে প্রসেসিং
          typeit: true
          social: true
          disclaimer: ""
